version: '3.3'

services:
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - my_dbdata:/var/lib/postgresql/data

volumes:
  my_dbdata:

  